drivers: power: Suppress int conversion error
I get this error with previous commit b4d530d89cc3

../drivers/base/power/wakeup.c:1178:81: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'void *' [-Werror,-Wint-conversion]
        debugfs_create_file("trace_marker", 0220, debugfs_create_dir("tracing", NULL), 1, NULL);
                                                                                       ^
../include/linux/debugfs.h:174:35: note: passing argument to parameter 'data' here
                                        struct dentry *parent, void *data,
                                                                     ^
1 error generated.

No clue how to solve properly

referenced: 1a091ef4951a